; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
board_build.partitions = huge_app.csv
board_build.esp-idf.sdkconfig_defaults = sdkconfig.defaults
upload_speed = 921600
framework = espidf, arduino
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps =
	esp32_https_server
	WiFi
	WiFiMulti
	ewpa/LibSSH-ESP32
	URLCode
    https://github.com/BojanJurca/Key-value-database-Arduino-Library-for-ESP32
monitor_speed = 115200
build_src_flags = 
    -Wno-class-memaccess
    -Wno-error=class-memaccess
build_flags = 
    -D FF_FS_EXFAT=1
    -D FF_LBA64=1
    -D FF_USE_TRIM=0
    -Wno-format
    -Wno-error=format
    -Wno-error=format=
    -Wno-format-security
    -Wno-class-memaccess
    -Wno-error=class-memaccess
	-DCMAKE_EXPORT_COMPILE_COMMANDS=1
	;-D CONFIG_ESP_SYSTEM_PANIC_PRINT_HALT=1
extra_scripts = pre:extra_script.py
monitor_filters = 
	esp32_exception_decoder
;	log2file

;ARDUINO_SKIP_TICK_CHECK=1 pio run -t menuconfig