; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
board_build.partitions = huge_app.csv
upload_speed = 921600
framework = espidf, arduino
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps =
	esp32_https_server
	WiFi
	WiFiMulti
	ewpa/LibSSH-ESP32
monitor_speed = 115200
build_flags =
    -DCONFIG_MBEDTLS_ASYMMETRIC_CONTENT_LEN=y
    -DCONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=4096
    -DCONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096
	-DCMAKE_EXPORT_COMPILE_COMMANDS=1
	-DCONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=8192
    -DHTTPS_BUF_SIZE=512
extra_scripts = pre:extra_script.py
monitor_filters = esp32_exception_decoder